### PR TITLE
Issue 87 - Maven support

### PR DESCRIPTION
**Pull request by DoubleDee73**
- added a pom.xml with dependencies to existiing libs and resources
- removed Apache Derby, jutils + jinput from resources and added dependency to pom.xml

### CODE REVIEW

**Comment by DoubleDee73** [comment]
Temporarily closed, as I found some issues with my branch

**Comment by DoubleDee73** [comment]
I have tried to find recent versions of the depended libraries.
If I could not find a match, I repackaged the existing classes into individual jars and removed the classes.
For the universal encoding detector, I moved the class into the src.
There are some libraries, I could not find recent versions for either, but they do not seem to be used, so I left the classes, at one point, it'd be a good idea to remove those.
Generally the libraries used are some 15 years old and it should be considered to switch to something more recent.

**Comment by SarutaSan72** [comment]
thanks, good work! I'm out of office for a while, testing this will take some time.

**Comment by DoubleDee73** [comment]
Hm. 
IntelliJ will compile and can start the application, it seems though, that Maven will not package all dependencies into a jar, when trying to create an installable application. I'm sure there's a way to do it, I'll have another look.

**Comment by SarutaSan72** [comment]
Not tested, therefore cannot merge. As discussed, please continue further improvements in your fork.

**Pull request closed without merging**
