### PR TITLE
Issue 124 - Default UTF8 handling

### PR DESCRIPTION
**Pull request by DoubleDee73**
This sets the "Always save as UTF-8" flag by default. It has no impact on how existing files are loaded into the File Cache. When these files are then modified, they will be saved as UTF-8
Additionally, txt-Files that had #ENCODING:UTF8 as the first line were not recognised as valid Ultrastar songs. This has been mitigated.

### CODE REVIEW

**Review by basisbit — APPROVED** [review]

**Comment by TeLiXj** [comment]
The UTF-8 encoding as default could be a good point but ENCODING tag isn't recognized by all UltraStar games, this can't be added by default. You can add it manually in the tags section in the options windows in your installation.
Additionally we could remove LENGTH and PREVIEWSTART one day because are in the same situation.

**Comment by DoubleDee73** [comment]
I'm not adding the #ENCODING tag to the txt. I'm adding the support of it at the beginning of the file.
I did have the problem that this tag was written at the beginning of a txt and Yass didn't recognize the file when the library was refreshed. I would then have to move that line manually

**Comment by TeLiXj** [comment]
Sorry, I didn't analyse correctly the code. But my argument is the same: we mustn't add non common tags. And now I can see too `AUTHOR` that was unused many many years ago... 
The solution could be to refactor that code to support configured tags in the tags section on options. Then you can add `ENCODING` or whatever you want.

**Comment by DoubleDee73** [comment]
Okay. I'm really irritated right now. This is a non breaking change which uses a tag, that is supported by USDX, which is the main application which is actually maintained.
Other software like Vocaluxe hasn't even reached a 1.0 release status, I frankly don't care. Especially as this isn't even writing the tag.

**Comment by TeLiXj** [comment]
The main application is UltraStar WorldParty for years that is mantained by UltraStar España team, we release many new versions with huge changes. USDX code is based in our old pre 2016 code win some minor changes, mainly related with FFMPEG or updated libraries. They can use his program as they want, they have their own editor and they can do all changes that they want on it. And in this case ENCODING tag is completely unnecessary. We can detect the codification of the txt file without it.
I'm clear: we don't want to add things only because USDX use it. Many years ago they decided to continue his own way and it's perfect, but they don't have the last word.

**Comment by basisbit** [comment]
@TeLiXj you violated GPL, so you technically / legally speaking may not even use the UltraStar code base any more.

But anyways, back to topic: The ultrastar txt file format allows the meta tags to be in any order, thus the suggested change in this here PR is correct / an improvement.
What maybe needs some discussion / testing (see related issue #124), is the change of `p.put("utf8-always", "false");` to `p.put("utf8-always", "true");`. This probably goes a bit further than the initially desired change. We are only deprecating support for non-UTF8-files, but not yet dropping it, and breaking encoding after reading not properly detected encoded files, that would be not desired as mentioned by @SarutaSan72.

To go forward, I'd suggest splitting this pull request into two separate ones, one for the default-utf8-change, and one for the header parsing change.

**Comment by DoubleDee73** [comment]
I see the whole picture now. Also for all my other PRs...
See, I was not around, when the communities seemed to have a fall out. I don't give a damn, which Ultrastar version is the "main" one and I apologize, that I didn't give your version the attention you think it deserves.
But quite honestly, I think this is silly. Yass should be independent from these versions in the way that it should have the highest compatibility with all of them (and afaik, USDX doesn't require #encoding either, but Vocaluxe does).
But feel free to close this PR or do whatever you like with it. After having discussed this with @SarutaSan72 , and I have no hard feelings towards him whatsoever, but the best course of action is, that I will simply work on my fork and do things the way I think benefits the majority of users. Then people can decide to use the original Yass, or "go rogue"...
I did not offer my support to discuss things longer than necessary. If my help is not wanted, I'll give it elsewhere.

**Comment by TeLiXj** [comment]
> @TeLiXj you violated GPL, so you technically / legally speaking may not even use the UltraStar code base any more.

I don't have anything to talk with you and less with your ego.

> I see the whole picture now. Also for all my other PRs...
See, I was not around, when the communities seemed to have a fall out. I don't give a damn, which Ultrastar version is the "main" one and I apologize, that I didn't give your version the attention you think it deserves.
But quite honestly, I think this is silly. Yass should be independent from these versions in the way that it should have the highest compatibility with all of them (and afaik, USDX doesn't require #encoding either, but Vocaluxe does).
But feel free to close this PR or do whatever you like with it. After having discussed this with @SarutaSan72 , and I have no hard feelings towards him whatsoever, but the best course of action is, that I will simply work on my fork and do things the way I think benefits the majority of users. Then people can decide to use the original Yass, or "go rogue"...
I did not offer my support to discuss things longer than necessary. If my help is not wanted, I'll give it elsewhere.

I don't care about the attention to our version, I only said that because you think that only USDX is the unique active project and we must change everything that they want. Performous (old UltraStar NG) use too the UltraStar format, and many other small projects. 
For that, I told you that the correct way to allow whatever tag you want in the header is create a new PR to refactor the code to allow any tag configured in Yass. By default the common tags used for all project and later every user can add as they want.
This PR can continue only with the original purpose that is enable UTF-8 by default and continue the discussion in the Issues section. 

Your help is very very welcome. Saruta don't have the time and energies to do as he wants, and me don't have enough knowledge to help as I want.

**Comment by SarutaSan72** [comment]
> Your help is very very welcome. Saruta don't have the time and energies to do as he wants

true

> splitting this pull request into two separate ones, one for the default-utf8-change, and one for the header parsing change.

please do so, the 2nd is fine, the 1st one is needs further testing

**Comment by DoubleDee73** [comment]
temporarily closing

**Comment by DoubleDee73** [comment]
Reverted changes for encoding check in header

**Comment by SarutaSan72** [comment]
>  After having discussed this with @SarutaSan72 , and I have no hard feelings towards him whatsoever, but the best course of action is, that I will simply work on my fork and do things the way I think benefits the majority of users. Then people can decide to use the original Yass, or "go rogue"...

Agreed, as discusssed. I won't have time (not much? not at all?) in near future for further development, so I wish you the best for your fork. Maybe when things get better I'll try to merge some of your improvements, or vice versa.

I cannot merge this change (set default encoding to UTF-8) because we could not determine that it does not destroy older files.
--> close

**Pull request closed without merging**
